### ISSUE TITLE
SSHD Log Support

### ISSUE THREAD

**Issue by 3dawg** [3dawg/nvccybersec-club#6]
SSH Log support should be added as a new module. As a reminder, you should have the following:

Must be able to:
-Grab unique IP addresses 
-Get failed login attempts and parse the ip addresses that are associated with those attempts
-Get successful login attempts and parse the ip addresses that are associated with those attempts
-Get port numbers that were attempted to be connected on
-Get list of users that were attempted to be authenticated

**Comment by ateschan** [comment]
- [x] Grab unique IP addresses
- [x] Get failed login attempts and parse the ip addresses that are associated with those attempts
- [x] Get successful login attempts and parse the ip addresses that are associated with those attempts
- [x] Get port numbers that were attempted to be connected on
- [x] Get list of users that were attempted to be authenticated
